services:
  forgejo-mirror-shadow:
    image: codeberg.org/forgejo/forgejo:15.0.3-rootless
    container_name: local-forgejo-mirror-shadow
    ports:
      - "127.0.0.1:13300:3000"
    volumes:
      - ./shadow/app.ini:/etc/gitea/app.ini
      - ./shadow/data:/var/lib/gitea
      - ./shadow/repos:/var/lib/gitea/git/repositories
      - ./shadow/log:/var/lib/gitea/log
    command: ["forgejo", "web", "--config", "/etc/gitea/app.ini"]
